// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjhrwkno-ngjfHf4iBUVGSJo9irp4F5nE',
    appId: '1:891646450039:web:2cb944f2490a27014da972',
    messagingSenderId: '891646450039',
    projectId: 'pesuclassroom',
    authDomain: 'pesuclassroom.firebaseapp.com',
    storageBucket: 'pesuclassroom.appspot.com',
    measurementId: 'G-97EK47NHL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzyaE_nsKQv095uzKFubbJN7r-Vj9iAIs',
    appId: '1:891646450039:android:b24c294c8e315b724da972',
    messagingSenderId: '891646450039',
    projectId: 'pesuclassroom',
    storageBucket: 'pesuclassroom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWdX7XiXjd5btxP3G098dtDCQAoOOHws',
    appId: '1:891646450039:ios:4cba6ff0d6b70a6d4da972',
    messagingSenderId: '891646450039',
    projectId: 'pesuclassroom',
    storageBucket: 'pesuclassroom.appspot.com',
    iosBundleId: 'com.example.pesuclassrooms',
  );
}
