CREATE TABLE IF NOT EXISTS Assignments (
  AssignmentId INT AUTO_INCREMENT PRIMARY KEY,
  ClassId INT NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Description TEXT,
  DueDate DATETIME,
  Attachment BLOB,
  PostedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ClassId) REFERENCES Classes(ClassId)
);


CREATE TABLE IF NOT EXISTS Submissions (
  SubmissionId INT AUTO_INCREMENT PRIMARY KEY,
  AssignmentId INT NOT NULL,
  UserId VARCHAR(30) NOT NULL,
  SubmissionText TEXT,
  SubmissionFileURL VARCHAR(255),
  SubmissionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (AssignmentId) REFERENCES Assignments(AssignmentId),
  FOREIGN KEY (UserId) REFERENCES User(UserId)
);

