CREATE TABLE IF NOT EXISTS User
(
  UserId VARCHAR(30) NOT NULL,
  FirstName VARCHAR(20) NOT NULL,
  LastName VARCHAR(20),
  Email VARCHAR(30) NOT NULL,
  JoiningDate DATE NOT NULL,
  photoUrl VARCHAR(30) NOT NULL,
  PRIMARY KEY (UserId),
  UNIQUE (Email)
);

CREATE TABLE Teacher
(
  TId VARCHAR(15) NOT NULL,
  CourseId VARCHAR(10) NOT NULL,
  Tid VARCHAR(15) NOT NULL,
  PRIMARY KEY (TId, CourseId),
  FOREIGN KEY (CourseId) REFERENCES Course(CourseId),
  FOREIGN KEY (Tid) REFERENCES User(UserId)
);